version: '2'
services:
    cepapp-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/cepapp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=cepapp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
